config/routes.rb
Sentrino::Application.routes.draw do
 
	root :to => "home#index"

  match '/users/:user_id/tasks/home' => 'tasks#home'
  match '/devices/:id/sensor_status' => 'devices#show_sensor_status'
  match '/devices/:id/task_status' => 'devices#show_task_status'

  devise_for :users, :path => 'accounts', :skip => [:sessions]
  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign_in' => 'devise/sessions#create', :as => :user_session
    get 'sign_up' => 'devise/registrations#new', :as => :new_user_session
    delete 'sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :index
  resources :application
  
  resources :devices do
    resources :actions
    resources :sensors
  end

  resources :users do
    resources :tasks
  end

  match '/settings' => 'home#settings'
  match "/runcron" => "tasks#cron"
end

app/models/task.rb
class Task < ActiveRecord::Base
  belongs_to :user
  has_many :task_actions
  has_many :task_sensors
  accepts_nested_attributes_for :task_actions, allow_destroy: true
  accepts_nested_attributes_for :task_sensors, allow_destroy: true

  attr_accessible :frequency, :name, :log_type, :task_actions_attributes, :task_sensors_attributes

  validates :name,  :presence => true
  validates :frequency,  :presence => true

  def all_involved_devices
  	devices = []
  	self.task_sensors.each do |sensor|
  		devices << sensor.device_id
  	end
  	self.task_actions.each do |action|
  		devices << action.device_id
  	end
  	devices
  end
end

app/models/task_action.rb
class TaskAction < ActiveRecord::Base
  belongs_to :task
  belongs_to :action

  attr_accessible :post_action, :parameters, :action_id

  validates :post_action,  :presence => true
  validates :parameters,  :presence => true

  def device_id
  	self.action.device_id
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
	before_filter :is_logged_in?
	before_filter :find_task, :only => [:show, :edit, :update, :destroy]

	def home
		@tasks = current_user.tasks
		@devices = current_user.devices
	end

	#ajax
	def index
		@tasks = current_user.tasks

		render :partial => "task_list"
	end

	#ajax
	def new
		@task = current_user.tasks.build
		@devices = current_user.devices

		render :partial => "form" 
	end
	
	#ajax
	def create
		@task = current_user.tasks.build(params[:task])

		if @task.save
			@status = {
				:status => true,
				:message => "Task has been scheduled.",
				:task => @task
			}
		else
			@status = {
				:status => false,
				:message => "Task has not been scheduled.",
				:task => nil
			}
		end
		render :json => @status
	end

	def edit
		render :partial => "form" 
	end
	
	def update
		if @task.update_attributes(params[:task])
			@status = {
				:status => true,
				:message => "Task has been updated.",
				:task => @task
			}
		else
			@status = {
				:status => false,
				:message => "Task has not been updated.",
				:task => nil
			}
		end
		render :json => @status
	end

	def destroy
		@task.destroy
		flash[:notice] = "Task has been deleted."
		redirect_to @device
	end

	def cron
		@tasks = Task.all
		@active_crons = get_active_crons()

		@tasks.each do |task|
			if @active_crons[task.frequency]
				result = task.device.send(task.action_type)
				if task.result_action == "email"
					#TODO
				elsif task.result_action == "store"
					#TODO
				end
			end
		end
	end

	private

		def find_task
			@task = Task.find(params[:id])
		end
		
		def is_logged_in?
		    unless !current_user.nil?
		      flash[:notice] = "You must be logged in to view that."
		      redirect_to root_path
		    end
		end
	    

		def get_active_crons
			@current_hour = Time.now.strftime("%H").to_i
			@current_minute = Time.now.strftime("%M").to_i

			return {
				"1M" => true,
				"5M" => @current_minute%5 == 0 ? true : false,
				"30M" => @current_minute%30 == 0 ? true : false,
				"1H" => @current_minute == 0 ? true : false,
				"12H" => @current_hour%12 == 0 && @current_minute == 0 ? true : false,
				"24H" => @current_hour == 0 && @current_minute == 0 ? true : false
			}
		end
end

app/views/tasks/_form.html.erb
<%= form_for [current_user, @task] do |f| %>
  <% if @task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
      <% @task.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  
  <div class="field">
    <%= f.label :frequency %>
    <%= f.select :frequency, [['1 Minute','1M'],['5 Minutes','5M'],['30 Minutes','30M'],['1 Hour', '1H'], ['12 Hours', '12H'],['24 Hours', '24H']] %>
  </div>

  <div class="dynamic-field-container">
    <h3>Sensors</h3>
    <%= link_to_add_fields "Add Sensor", f, :task_sensors %>
    <%= f.fields_for :task_sensors do |builder| %>
      <%= render 'task_sensor_fields', f: builder %>
    <% end %>
  </div>

  <div class="dynamic-field-container">
    <h3>Actions</h3>
    <%= link_to_add_fields "Add Action", f, :task_actions %>
    <%= f.fields_for :task_actions do |builder| %>
      <%= render 'task_action_fields', f: builder %>
    <% end %>
  </div>

  <div class="actions">
    <button style="width:225px;" type="button" id="task_submit" class="btn btn-primary">Go</button>
  </div>
<% end %>

app/views/tasks/_task_action_fields.html.erb
<fieldset>
  <%= f.label :action_id, "Action" %><br />
  <%= f.collection_select(:action_id, current_user.actions, :id, :combined_name)%><br />
  <%= f.label :parameters, "Parameters" %><br />
  <%= f.text_field :parameters %><br />
  <%= f.label :post_action, "Do this with result:" %><br />
  <%= f.select :post_action, [['Log','log'],['Email','email']] %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</fieldset>

app/views/tasks/_task_list.html.erb
<ul id="task_list">
	<% @tasks.each do |task| %>
		<li class="task-list-item btn-primary" data-id="<%= task.id %>">
			<%= task.name %>
		</li>
	<% end %>
</ul>

app/views/tasks/_task_sensor_fields.html.erb
<fieldset>
  <%= f.label :sensor_id, "Sensor" %><br />
  <%= f.collection_select(:sensor_id, current_user.sensors, :id, :combined_name)%><br />
  <%= f.label :post_action, "Do this with result:" %><br />
  <%= f.select :post_action, [['Log','log'],['Email','email']] %>
  <%= f.check_box :_destroy %>
  <%= f.label :_destroy, "Remove" %>
</fieldset>

app/views/tasks/edit.html.erb
<%= render "form" %>

app/views/tasks/home.html.erb
<%= content_tag "section", id: "task_form", class: "task-form", data: {new_url: new_user_task_path(current_user), edit_url: user_path(current_user) + "/tasks/?/edit"} do %>

<% end %>

<%= content_tag "section", id: "task_index", class: "task-list", data: {new_url: user_tasks_path(current_user)} do %>

<% end %>

app/views/tasks/new.html.erb
<%= render "form" %>

app/views/tasks/show.html.erb
<%= @task.name %><br />
<%= @task.frequency %><br />

Tasks<br />
<% @task.task_actions.each do |task_action|%>
  <%= task_action.action_id %><br />
<% end %>

Sensors<br />
<% @task.task_sensors.each do |task_sensor|%>
  <%= task_sensor.sensor_id %><br />
<% end %>