config/routes.rb
Sentrino::Application.routes.draw do
 
	root :to => "home#index"

  match '/users/:user_id/tasks/home' => 'tasks#home'
  match '/devices/:id/sensor_status' => 'devices#show_sensor_status'
  match '/devices/:id/task_status' => 'devices#show_task_status'

  devise_for :users, :path => 'accounts', :skip => [:sessions]
  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign_in' => 'devise/sessions#create', :as => :user_session
    get 'sign_up' => 'devise/registrations#new', :as => :new_user_session
    delete 'sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :index
  resources :application
  
  resources :devices do
    resources :actions
    resources :sensors
  end

  resources :users do
    resources :tasks
  end

  match '/settings' => 'home#settings'
  match "/runcron" => "tasks#cron"
end

app/models/device.rb
class Device < ActiveRecord::Base
  attr_accessible :nickname, :model, :ip, :user_id, :image, :port

  has_many :actions
  has_many :action_types, :through => :actions

  has_many :sensors 
  has_many :sensor_types, :through => :sensors

  has_many :tasks
  belongs_to :user
 
  validates :model,  :presence => true

  @ip_regex = /^([1-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])(\.([0-9]|[1-9][0-9]|1[0-9][0-9]|2[0-4][0-9]|25[0-5])){3}$/
  validates :ip, :presence => true,
                 :length => { :minimum => 8 },
                 :format => { :with => @ip_regex, :message => "Invalid IP address. Must be in format: X.X.X.X "}

  UNSUPPORTED_METHOD_MESSAGE = "Unsupported on this device."
  PARSE_ERROR_MESSAGE = "Problem decoding response."

  # Methods related to actual device communications below

  #Sensors
  def status
    response = communicateWithDevice("ping");
    if response
      response["err"] ? UNSUPPORTED_METHOD_MESSAGE : "Online"
    else
      return PARSE_ERROR_MESSAGE
    end
  end

  def temp
    response = communicateWithDevice("temp");
    if response
      response["err"] ? UNSUPPORTED_METHOD_MESSAGE : (response["temp"].to_f / 100).to_s + "&deg;F"
    else
      return PARSE_ERROR_MESSAGE
    end
  end

  def humidity
    response = communicateWithDevice("hmdy");
    if response
      response["err"] ? UNSUPPORTED_METHOD_MESSAGE : (response["hmdy"].to_f / 100).to_s + "%"
    else
      return PARSE_ERROR_MESSAGE
    end
  end

  #Actions
  def beep
    response = communicateWithDevice("beep");
    if response
      response["err"] ? UNSUPPORTED_METHOD_MESSAGE : true;
    else
      return PARSE_ERROR_MESSAGE
    end
  end

  def light(duration = 5)
    response = communicateWithDevice("lght", duration);
    if response
      response["err"] ? UNSUPPORTED_METHOD_MESSAGE : true;
    else
      return PARSE_ERROR_MESSAGE
    end
  end

  private
    def communicateWithDevice(method, args = nil)
      begin
        url = "http://#{self.ip}:#{self.port || '80'}/$$#{method}"
        if args then url += "/%%#{args}" end

        p "Fetching #{url}"
        response = JSON.parse(HTTParty.get(url, {:timeout => 5000}));
        return false unless response
        return response["error"] if response["error"]["err"] == true
	      return response["body"]
      rescue
        return false
      end
    end

end

app/controllers/devices_controller.rb
class DevicesController < ApplicationController
  before_filter :is_logged_in?
  before_filter :find_device, :only => [:show, :edit, :update, :destroy, :show_sensor_status, :show_task_status]
  
  # GET /devices
  def index
    @devices = Device.where(:user_id => current_user[:id])
  end

  # GET /devices/1
  def show
    @sensor_replies = {}
    @device.sensor_types.each do |sensor_type|
      reply = @device.send(sensor_type.method)
      @sensor_replies[sensor_type.name] = reply ? reply : "N/A" 
    end

    @tasks = current_user.tasks  
  end

  # GET /devices/new
  def new
    @device = Device.new
  end

  # GET /devices/1/edit
  def edit
  end

  # POST /devices
  def create
    @device = Device.new(params[:device].merge :user_id => current_user[:id])
    if @device.save
      if register_sensors(@device) && register_actions(@device)
        redirect_to '/', notice: 'Device was successfully created, and its sensors/actions have been automatically registered.' 
      else
        redirect_to '/', notice: 'Device was successfully created.  We were not able to automatically register sensors/actions for the device.'
      end
    else
      render action: "new" 
    end
  end

  # PUT /devices/1
  def update
    if @device.update_attributes(params[:device])
      redirect_to '/', notice: 'Device was successfully updated.'
    else
      render action: "edit" 
    end
  end

  # DELETE /devices/1
  def destroy
    @device.destroy
    redirect_to '/', notice: 'Device was deleted.'
  end

  def show_sensor_status
    render :partial => "sensor_status"
  end

  def show_task_status
    @tasks = []
    current_user.tasks.each do |task|
      if task.all_involved_devices.include?(params[:id].to_i)
        @tasks << task
      end
    end

    render :partial =>  "task_status"
  end
  
  private
    def find_device
      @device = current_user.devices.find(params[:id])
      rescue ActiveRecord::RecordNotFound
        flash[:alert] = "The device you were looking for could not be found."
        redirect_to devices_path
    end
    
    def is_logged_in?
      unless !current_user.nil?
        flash[:notice] = "You must be logged in to view that."
        redirect_to root_path
      end
    end

    def register_sensors(device)
      SensorType.all.each do |sensortype|
        reply = device.send(sensortype[:method])
        if reply != "Problem decoding response."
          @sensor = device.sensors.build
          @sensor[:sensor_type_id] = sensortype[:id]
          @sensor.save
        end
      end
      return true
    end

    def register_actions(device)
      ActionType.all.each do |actiontype|
        reply = device.send(actiontype[:method])
        if reply != "Problem decoding response."
          @action = device.actions.build
          @action[:action_type_id] = actiontype[:id]
          @action.save
        end
      end
      return true
    end

end

app/helpers/devices_helper.rb
module DevicesHelper
end

app/views/devices/_form.html.erb
<%= form_for(@device) do |f| %>
  <% if @device.errors.any? %>
    <div id="error_explanation" class="alert alert-error">
      <h2><%= pluralize(@device.errors.count, "error") %> prohibited this device from being saved:</h2>

      <ul>
      <% @device.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.text_field :model %>
  </div>

  <div class="field">
    <%= f.label :ip %>
    <%= f.text_field :ip %>
    <label for="port" id="port_label">:</label><%= f.text_field :port, :placeholder => 'port (optional)' %>
  </div>
  
  <div class="actions">
    <%= f.submit :class => "btn btn-primary btn-large" %>
  </div>
<% end %>

app/views/devices/_list_item.html.erb
<article class="device-list-item" id="<%= device.id %>">
    <div class="inner">

      <header class="device-header">
        <h3 class="device-title"><%= device.nickname %></h3>
    
        <p>Model: <%= device.model %></p>
        <p>Ip: <%= device.ip %></p>
      </header>

      <div class="device-body">

        <ul class="device-readings half-column">
        </ul>

        <ul class="device-tasks half-column">
        </ul>

      </div>

      <footer class="device-footer">

        <%= link_to "", :rel => "tooltip", :title => "Refresh", :class => "fleft" do %>
          <i class="icon-refresh"></i>
        <% end %>

        <button class="btn center-block">Control (Coming soon)</button>

        <%= link_to edit_device_path(device), :rel => "tooltip", :title => "Edit", :class => "fright" do %>
          <i class="icon-pencil"></i>
          <span>Edit</span>  
        <% end %>

      </footer>

    </div>
  </article>

app/views/devices/_sensor_status.html.erb
<% @device.sensors.each do |sensor| %>
	<li><b><%= sensor.name %>:</b> <%= @device.send(sensor.method).html_safe %></li>
<% end %>

app/views/devices/_task_status.html.erb
<% @tasks.each do |task| %>
	<li>
		<b><%= task.name %></b>
		 - 
		<%= task.frequency %>
	</li>
<% end %>

app/views/devices/edit.html.erb
<div class="device-form">
	<h1>Editing device</h1>
	
	<%= render 'form' %>
	
	<div class="device-actions">
		<%= link_to raw('<i class="icon-home"></i>'), "/", :class=>"btn" %>
		<%= link_to raw('<i class="icon-eye-open"></i>'), @device, :class => "btn" %>
		<%= link_to raw('<i class="icon-remove"></i>'), @device, method: :delete, data: { confirm: 'Are you sure?' }, :class=>"btn btn-danger" %>
	</div>
</div>

app/views/devices/index.html.erb
<div class="device-list">
  <% @devices.each do |device| %>
    
    <%= render :partial => 'devices/list_item', :locals => { :device => device } %>

  <% end %>
</div>

app/views/devices/new.html.erb
<section class="device-form">
	<h1>New device</h1>
	
	<%= render 'form' %>
		
	<%= link_to 'Back', "/" %>
</section>

app/views/devices/show.html.erb
<div id="device-show">
	<div id="primary">

		<div class="device-image"></div>

		<h1><%= @device.nickname %></h1>

		<p><b>Model:</b> <%= @device.model %></p>
		<p><b>Ip:</b> <%= @device.ip %></p>

		<div class="action-replies">
			<% @sensor_replies.each do |name, reply|%>
				<%= name %>: <%= reply.html_safe %><br />
			<% end %>
		</div>

		<div class="device-actions">
			<%= link_to raw('<i class="icon-pencil"></i> Edit'), edit_device_path(@device) %>
			<%= link_to raw('<i class="icon-remove"></i> Remove'), @device, method: :delete,
			data: { confirm: 'Are you sure you want to delete this device?' },
			:class => "danger" %>
		</div>

	</div>

	<div id="tasks">
		<div class="header-wrap">
			<h2>Tasks</h2>
		</div>
		
		<% @tasks.each do |task| %>
			<div class="task-list-item">
				<h4><%= task.name %></h4>
				<%= task.frequency %> -
				<%= task.action_type.name %>
				<%= link_to raw('<i class="icon-pencil"></i>'), edit_polymorphic_path([@device, task]) %>
			</div>
			<% sleep(1) %>
		<% end %>

		<div class="new-task">
			<%= link_to "New Task", new_device_task_path(@device), :class => "btn btn-primary btn-large" %>
		</div>
	</div>

	<div class="clear"></div>

</div>