config/routes.rb
Sentrino::Application.routes.draw do
 
	root :to => "home#index"

  match '/users/:user_id/tasks/home' => 'tasks#home'
  match '/devices/:id/sensor_status' => 'devices#show_sensor_status'
  match '/devices/:id/task_status' => 'devices#show_task_status'

  devise_for :users, :path => 'accounts', :skip => [:sessions]
  as :user do
    get 'sign_in' => 'devise/sessions#new', :as => :new_user_session
    post 'sign_in' => 'devise/sessions#create', :as => :user_session
    get 'sign_up' => 'devise/registrations#new', :as => :new_user_session
    delete 'sign_out' => 'devise/sessions#destroy', :as => :destroy_user_session
  end

  resources :index
  resources :application
  
  resources :devices do
    resources :actions
    resources :sensors
  end

  resources :users do
    resources :tasks
  end

  match '/settings' => 'home#settings'
  match "/runcron" => "tasks#cron"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery

  def index
  	if user_signed_in?
  		@devices = Device.where(:user_id => current_user[:id])
  		render :template => 'home/dashboard'
  	else
  		render :template => 'home/index'
  	end
  end

  def settings
    render :partial => "shared/settings"
  end
end

app/views/home/dashboard.html.erb
<section class="dashboard-wrap">
	<div class="welcome">
		<h1>Welcome, <%= current_user.email %></h1>
	</div>

	<div class="device-list-header">
		<h2>Your devices</h2>
	</div>

	<%= render :template => "devices/index" %>
	
	<%= link_to 'Add a Device', new_device_path, :class => "btn btn-primary btn-large" %>
	<%= link_to 'Tasks', user_path(current_user) + "/tasks/home", :class => "btn btn-primary btn-large" %>
</section>

app/views/home/index.html.erb
<header id="overview" class="hero-unit">
	<h1>Sentrino</h1>
	<p>Interfacing and automation with Arduino, Raspberry Pi, and more.</p>
	<p><%= link_to "Sign up", "/users/sign_up", :class=>"btn btn-primary btn-large" %></p>
</header>